# leopard/isolation/Makefile

ISOLATION_OPTS = --load-extension=leopard
ISOLATION_OPTS += --temp-config $(top_srcdir)/leopard/isolation/leopard.conf
ISOLATION_OPTS += --temp-config $(top_srcdir)/leopard/isolation/isolation.conf
ISOLATION = <ISOLATION_TESTS>
