#-------------------------------------------------------------------------
#
# Makefile for src/pl/plsql (PostgreSQL's SQL procedural language)
#
# Copyright (c) 1994, Regents of the University of California
#
# src/pl/plsql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/pl/plsql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

$(recurse)
